#========================================
# Test profile settings (IT tests)
#========================================
logging:
  level:
    root: INFO
integration:
  ssbtek:
    url: http://localhost:${wiremock.server.port}/ssbtek
    connect-timeout: 5
    read-timeout: 30
